version: '3'
services:
  app:
    build:
      context: .
    container_name: docker-fwp-app
    env_file:
      - ./environments/.env
    command: bundle exec puma -C config/puma.rb
    # command: >
    #   sh -c "bundle exec rake assets:precompile &&
    #          bundle exec puma -C config/puma.rb"
    volumes:
      - .:/webapp
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
      - log-data:/webapp/log
  web:
    build:
      context: containers/nginx
    container_name: docker-fwp-web
    volumes:
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data: